sudo: required

services:
    - docker

matrix:
  include:
    - elixir_test:
      env:
        - TEST=elixir_test
        - MIX_EXS=${HOME}/elixir/elixir_advent/mix.exs
      language: elixir
      elixir: 1.7.4
      script: ./gradlew elixir:test
    - java_test:
      env: TEST=java_test
      language: java
      jdk: oraclejdk11
      script: ./gradlew java:test
    - python_pytest:
      env: TEST=python_pytest
      language: python
      script: ./gradlew python:pytest
    - python_pylint:
      env: TEST=python_lint
      language: python
      script: ./gradlew python:pylint
    - rust_test:
      env: TEST=rust_test
      language: rust
      script: ./gradlew rust:test


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/rust/.cargo/
