sudo: required

services:
  - docker

jobs:
  include:
    # Elixir testing in Travis is broken in this repo... will re-attempt resolution later
    # - name: "Elixir Tests"
    #   if: branch =~ .*elixir.* OR NOT branch =~ .*(python|rust|elixir|java).*
    #   language: elixir
    #   elixir: 1.7.4
    #   env: MIX_EXS="$(pwd)/elixir/elixir_advent/mix.exs"
    #   script: ./gradlew elixir:test

    - name: "Python Tests"
      if: branch =~ .*python.* OR NOT branch =~ .*(python|rust|elixir|java).*
      language: python
      script: ./gradlew python:pytest
    - name: "Python Lint"
      if: branch =~ .*python.* OR NOT branch =~ .*(python|rust|elixir|java).*
      language: python
      script: ./gradlew python:pylint

    - name: "Java Tests"
      if: branch =~ .*java.* OR NOT branch =~ .*(python|rust|elixir|java).*
      language: java
      jdk: oraclejdk11
      script: ./gradlew java:test

    - name: "Rust Tests"
      if: branch =~ .*rust.* OR NOT branch =~ .*(python|rust|elixir|java).*
      language: rust
      script: ./gradlew rust:test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/rust/.cargo/
