version: '2'
services:
  test_container:
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - TOXENV
    volumes:
      - .:/code_advent
    command: 'sh -c "pip install -r test-requirements.txt && tox"'
